In [2]:
import numpy as np

from sklearn.neighbors import KNeighborsClassifier

from sklearn import datasets

d:\python3.6.8\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


![](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1574058780346&di=e7df2620eb8a6cea7cbb1067c99e57bc&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201701%2F27%2F20170127084705_nSrBk.jpeg)

In [4]:
# 鸢尾花，因为自然环境不同，所以类别可以细分
iris = datasets.load_iris()
X = iris['data']
y = iris['target']
# 150代表着150个样本，4代表着4个属性：花萼长、宽；花瓣长、宽
X.shape

(150, 4)

In [6]:
# 将数据划分，一分为二：一部分用于训练，另一部分用测试
# 将顺序打乱
index = np.arange(150)
index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [7]:
# 打乱顺序
np.random.shuffle(index)
index

array([  3, 109, 118,  65,  46, 122,  26,  97, 133,  64, 114, 145, 110,
       119,  33,  36,  40, 111,  82, 129,  66,  15, 127,  81, 135, 112,
        39,  30, 107,  75,  28, 105,  27, 103, 148,  93,  10,  63,  86,
        52, 139, 124,  24,  90, 115, 149,  42,  84,  18, 143, 132,  94,
       137,  77,  62,  78,  41, 123,   5,  56,   7,  68, 142,  37,   9,
         1, 134,  51,  95,  49,  92,  34,  98, 117,  87,  89, 144,  44,
        59, 100,   6, 130,  58,  74, 146,  67, 102, 125,   4,   8,   0,
        69,  72,  29,  20, 128, 126,  76,  22,  70,  14,  25,  11, 101,
       136,  91,  43,  48,  54, 140,  13,  35,  17,  16, 138,  55,  99,
        60, 116,  38,  83,  31, 113,  88,  73, 104,  80,  71, 141,  19,
        23, 131,  32,  57,  85, 108,  96,  50,  12,  45,  47, 106, 147,
         2,  61, 121, 120,  53,  79,  21])

In [11]:
# 150个数据将打乱顺序100个取出来，算法学习，留下50个使用算法预测(验证算法是否可靠)
# 应用到实际中，要获取现实中的数据，算法对数据进行分类-------->上线：实时进行分类
X_train,X_test = X[index[:100]],X[index[100:]]

y_train,y_test = y[index[:100]],y[index[-50:]]

In [43]:
# 数据简单，只有4个属性
# p = 1 距离度量采用的是：曼哈顿距离
# p = 2 距离度量采用的是：欧氏距离
# 100**0.5 = 10
knn = KNeighborsClassifier(n_neighbors= 5,weights='distance',p = 1,n_jobs = 4)

knn.fit(X_train,y_train)

y_ = knn.predict(X_test)

knn.score(X_test,y_test)

0.96

In [20]:
y_

array([0, 0, 0, 2, 2, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1, 2, 0, 2, 0,
       2, 1, 1, 2, 1, 1, 2, 0, 0, 2, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 2, 0,
       1, 2, 2, 1, 1, 0])

In [19]:
# 算法返回的结果，使用 bianliang_接收：约定俗成变量命名规则
proba_ = knn.predict_proba(X_test)
proba_

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.2, 0.8],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. 

In [22]:
iris.target_names
# setosa --- 0
# versicolor  = 1
# virginica = 2

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [21]:
# 返回最大值的索引，鸢尾花的类别
proba_.argmax(axis = 1)

array([0, 0, 0, 2, 2, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1, 1, 1, 2, 0, 2, 0,
       2, 1, 1, 2, 1, 1, 2, 0, 0, 2, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 2, 0,
       1, 2, 2, 1, 1, 0], dtype=int64)

In [18]:
# 进行了封装
knn.score(X_test,y_test)

0.96

In [13]:
# 对比，看算法，预测的和真实的结果，是否对应
# 对应，大部分正确：算法没问题
# 不然，说明算法效果不好
print(y_)
print('--------------')
print(y_test)

[0 0 0 2 2 1 0 0 1 2 0 0 0 0 2 1 1 1 2 0 2 0 2 1 1 2 1 1 2 0 0 2 0 1 1 2 1
 1 0 0 0 1 2 0 1 2 2 1 1 0]
--------------
[0 0 0 2 2 1 0 0 1 2 0 0 0 0 2 1 1 1 2 0 1 0 2 1 1 2 1 1 2 0 0 2 0 1 1 2 1
 1 0 0 0 2 2 0 1 2 2 1 1 0]


In [17]:
# 准确率
(y_ == y_test).sum()/50

0.96