In [19]:
import numpy as np

import pandas as pd

from pandas import Series,DataFrame

from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split

# grid网格，search搜索，cv：cross_validation
# 搜索算法最合适的参数
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import accuracy_score

### 加载数据和提取数据和目标值

In [24]:
cancer = pd.read_csv('./cancer.csv',sep = '\t')
cancer.drop('ID',axis = 1,inplace=True)

X = cancer.iloc[:,1:]

y = cancer['Diagnosis']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

### 网格搜索GridSearchCV进行最佳参数的查找

In [25]:
knn = KNeighborsClassifier()

params = {'n_neighbors':[i for i in range(1,30)],
          'weights':['distance','uniform'],
          'p':[1,2]}

# cross_val_score类似
gcv = GridSearchCV(knn,params,scoring='accuracy',cv = 6)

gcv.fit(X_train,y_train)

GridSearchCV(cv=6, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 'weights': ['distance', 'uniform'], 'p': [1, 2]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

### 查看了GridSearchCV最佳的参数组合

In [15]:
gcv.best_params_

{'n_neighbors': 12, 'p': 1, 'weights': 'distance'}

In [13]:
gcv.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=12, p=1,
           weights='distance')

In [14]:
gcv.best_score_

0.9494505494505494

### 使用GridSearchCV进行预测，计算准确率

In [27]:
y_ = gcv.predict(X_test)

(y_ == y_test).mean()

0.9122807017543859

In [28]:
gcv.score(X_test,y_test)

0.9122807017543859

In [29]:
accuracy_score(y_test,y_)

0.9122807017543859

In [26]:
# 取出了最好的模型，进行预测
# 也可以直接使用gcv进行预测，结果一样的
knn_best = gcv.best_estimator_
y_ = knn_best.predict(X_test)
accuracy_score(y_test,y_)

0.9122807017543859

### 交叉表

In [33]:
X_test.shape

(114, 30)

In [32]:
pd.crosstab(index = y_test,columns=y_,rownames=['True'],colnames=['Predict'],
            margins=True)

Predict   B   M  All
True                
B        77   2   79
M         8  27   35
All      85  29  114

In [34]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_)

array([[77,  2],
       [ 8, 27]], dtype=int64)

In [38]:
# 真实的
y_test.value_counts()

B    79
M    35
Name: Diagnosis, dtype: int64

In [40]:
# 预测
Series(y_).value_counts()

B    85
M    29
dtype: int64

In [41]:
confusion_matrix(y_test,y_)

array([[77,  2],
       [ 8, 27]], dtype=int64)

In [46]:
confusion_matrix(y_,y_test)

array([[77,  8],
       [ 2, 27]], dtype=int64)

In [44]:
np.round(77/79,2)

0.97

In [45]:
np.round(27/35,2)

0.77

In [47]:
# precision
np.round(77/85,2)

0.91

In [48]:
np.round(27/29,2)

0.93

In [49]:
np.round(2*0.97*0.91/(0.97 + 0.91),2)

0.94

In [50]:
np.round(2*0.93*0.77/(0.77 + 0.93),2)

0.84

In [36]:
# 精确率、召回率、f1-score调和平均值
from sklearn.metrics import classification_report

print(classification_report(y_test,y_,target_names = ['B','M']))

              precision    recall  f1-score   support

           B       0.91      0.97      0.94        79
           M       0.93      0.77      0.84        35

   micro avg       0.91      0.91      0.91       114
   macro avg       0.92      0.87      0.89       114
weighted avg       0.91      0.91      0.91       114



### 提升准确率，提升精确率，提升召回率

In [51]:
X.head()

radius_mean  ...  fractal_max
0        17.99  ...      0.11890
1        20.57  ...      0.08902
2        19.69  ...      0.08758
3        11.42  ...      0.17300
4        20.29  ...      0.07678

[5 rows x 30 columns]

In [53]:
# 归一化操作
X_norm1 = (X - X.min())/(X.max() - X.min())
X_norm1.head()

radius_mean  ...  fractal_max
0     0.521037  ...     0.418864
1     0.643144  ...     0.222878
2     0.601496  ...     0.213433
3     0.210090  ...     0.773711
4     0.629893  ...     0.142595

[5 rows x 30 columns]

In [54]:
X_train,X_test,y_train,y_test = train_test_split(X_norm1,y,test_size  = 0.2)

knn = KNeighborsClassifier()

params = {'n_neighbors':[i for i in range(1,30)],
          'weights':['uniform','distance'],
          'p':[1,2]}
gcv = GridSearchCV(knn,params,scoring='accuracy',cv = 6)
gcv.fit(X_train,y_train)

GridSearchCV(cv=6, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 'weights': ['uniform', 'distance'], 'p': [1, 2]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [55]:
y_ = gcv.predict(X_test)
accuracy_score(y_test,y_)

0.9824561403508771

In [57]:
print(classification_report(y_test,y_,target_names=['B','M']))

              precision    recall  f1-score   support

           B       0.99      0.99      0.99        72
           M       0.98      0.98      0.98        42

   micro avg       0.98      0.98      0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



In [58]:
# Z-Score归一化，标准化
X_norm2 = (X - X.mean())/X.std()
X_norm2.head()

radius_mean  ...  fractal_max
0     1.096100  ...     1.935312
1     1.828212  ...     0.280943
2     1.578499  ...     0.201214
3    -0.768233  ...     4.930672
4     1.748758  ...    -0.396751

[5 rows x 30 columns]

In [60]:
X_norm2.mean()

radius_mean        -3.136331e-15
texture_mean       -6.558316e-15
perimeter_mean     -7.012551e-16
area_mean          -8.339355e-16
smoothness_mean     6.120470e-15
compactness_mean   -1.074321e-15
concavity_mean     -4.031144e-16
concave_mean        1.006030e-15
symmetry_mean      -1.888550e-15
fractal_mean        4.860396e-16
radius_sd          -9.998836e-16
texture_sd         -9.782255e-16
perimeter_sd        1.903086e-15
area_sd            -7.423275e-16
smoothness_sd      -7.449006e-16
compactness_sd     -3.976511e-16
concavity_sd        1.098906e-15
concave_sd         -2.766777e-16
symmetry_sd        -3.459447e-16
fractal_sd         -3.512129e-18
radius_max         -2.346102e-15
texture_max         1.761138e-15
perimeter_max      -1.214416e-15
area_max            5.919889e-16
smoothness_max     -5.033661e-15
compactness_max    -2.118204e-15
concavity_max       6.649631e-16
concave_max        -1.795088e-16
symmetry_max       -2.481734e-15
fractal_max         2.424930e-15
dtype: flo

In [59]:
X_norm2.std()

radius_mean         1.0
texture_mean        1.0
perimeter_mean      1.0
area_mean           1.0
smoothness_mean     1.0
compactness_mean    1.0
concavity_mean      1.0
concave_mean        1.0
symmetry_mean       1.0
fractal_mean        1.0
radius_sd           1.0
texture_sd          1.0
perimeter_sd        1.0
area_sd             1.0
smoothness_sd       1.0
compactness_sd      1.0
concavity_sd        1.0
concave_sd          1.0
symmetry_sd         1.0
fractal_sd          1.0
radius_max          1.0
texture_max         1.0
perimeter_max       1.0
area_max            1.0
smoothness_max      1.0
compactness_max     1.0
concavity_max       1.0
concave_max         1.0
symmetry_max        1.0
fractal_max         1.0
dtype: float64

In [61]:
X_train,X_test,y_train,y_test = train_test_split(X_norm2,y,test_size  = 0.2)

knn = KNeighborsClassifier()

params = {'n_neighbors':[i for i in range(1,30)],
          'weights':['uniform','distance'],
          'p':[1,2]}
gcv = GridSearchCV(knn,params,scoring='accuracy',cv = 6)
gcv.fit(X_train,y_train)

y_ = gcv.predict(X_test)
accuracy_score(y_test,y_)

0.9912280701754386

In [62]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [63]:
# MinMaxScaler 和最大值最小值归一化效果一样
mms = MinMaxScaler()

In [69]:
((X - X.min())/(X.max() - X.min())).head()

radius_mean  ...  fractal_max
0     0.521037  ...     0.418864
1     0.643144  ...     0.222878
2     0.601496  ...     0.213433
3     0.210090  ...     0.773711
4     0.629893  ...     0.142595

[5 rows x 30 columns]

In [70]:
mms.fit(X)
X2 = mms.transform(X)
X2.round(6)

array([[0.521037, 0.022658, 0.545989, ..., 0.912027, 0.598462, 0.418864],
       [0.643144, 0.272574, 0.615783, ..., 0.639175, 0.23359 , 0.222878],
       [0.601496, 0.39026 , 0.595743, ..., 0.835052, 0.403706, 0.213433],
       ...,
       [0.455251, 0.621238, 0.445788, ..., 0.487285, 0.128721, 0.151909],
       [0.644564, 0.66351 , 0.665538, ..., 0.910653, 0.497142, 0.452315],
       [0.036869, 0.501522, 0.02854 , ..., 0.      , 0.257441, 0.100682]])

In [72]:
# DataFrame,默认保留6位
# z = (x - u) / s
((X - X.mean())/X.std()).head()

radius_mean  ...  fractal_max
0     1.096100  ...     1.935312
1     1.828212  ...     0.280943
2     1.578499  ...     0.201214
3    -0.768233  ...     4.930672
4     1.748758  ...    -0.396751

[5 rows x 30 columns]

In [74]:
nd = X.get_values()
nd

d:\python3.6.8\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.values' or 'np.asarray(..)' instead.
  """Entry point for launching an IPython kernel.


array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [75]:
(nd - nd.mean(axis = 0))/nd.std(axis = 0)

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [76]:
ss = StandardScaler()

X3 = ss.fit_transform(X)
X3

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])