In [1]:
import numpy as np

import pandas as pd

from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split

# cv int 6 数据分分成6份
from sklearn.model_selection import cross_val_score,GridSearchCV

# KFold、StratifiedKFold将数据分成多少份
from sklearn.model_selection import KFold,StratifiedKFold

d:\python3.6.8\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
d:\python3.6.8\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
data = np.random.randint(0,10,size = (8,2))

target = np.array([0,0,1,0,1,1,1,0])
display(data,target)

array([[7, 8],
       [6, 6],
       [1, 5],
       [1, 3],
       [7, 8],
       [2, 1],
       [0, 3],
       [5, 2]])

array([0, 0, 1, 0, 1, 1, 1, 0])

In [9]:
train_test_split(data,target)

[array([[2, 1],
        [1, 5],
        [7, 8],
        [5, 2],
        [6, 6],
        [7, 8]]), array([[0, 3],
        [1, 3]]), array([1, 1, 0, 0, 0, 1]), array([1, 0])]

In [18]:
kFold = KFold(n_splits=4)

# train，test是索引，只要有索引可以获取数据
for train,test in kFold.split(data,target):
    print(target[train],target[test])

[1 0 1 1 1 0] [0 0]
[0 0 1 1 1 0] [1 0]
[0 0 1 0 1 0] [1 1]
[0 0 1 0 1 1] [1 0]


In [20]:
# 分成4份，每一份数据特征，数据样本比例和原来一样的
sKFold = StratifiedKFold(n_splits=4)
for train,test in sKFold.split(data,target):
    print(target[train],target[test])

[0 0 1 1 1 0] [0 1]
[0 1 0 1 1 0] [0 1]
[0 0 1 1 1 0] [0 1]
[0 0 1 0 1 1] [1 0]


In [ ]:
# train_test_split,KFold,StratifiedKFold左右都是将数据拆分

In [21]:
data = pd.read_csv('./salary.txt')

data.head()

age         workclass  final_weight  education  education_num  \
0   39         State-gov         77516  Bachelors             13   
1   50  Self-emp-not-inc         83311  Bachelors             13   
2   38           Private        215646    HS-grad              9   
3   53           Private        234721       11th              7   
4   28           Private        338409  Bachelors             13   

       marital_status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital_gain  capital_loss  hours_per_week native_country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [22]:
data.columns

Index(['age', 'workclass', 'final_weight', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'salary'],
      dtype='object')

In [23]:
data.drop(labels=['final_weight','education','capital_gain','capital_loss'],
          axis = 1,
          inplace=True)

In [24]:
data.shape

(32561, 11)

In [25]:
data.head()

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race     sex  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Black    Male              40   
4     Prof-specialty           Wife  Black  Female              40   

  native_country salary  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4           Cuba  <=50K

In [26]:
X = data.iloc[:,0:-1]

y = data['salary']

In [27]:
knn = KNeighborsClassifier()

knn.fit(X,y)

ValueError: could not convert string to float: 'State-gov'

In [ ]:
# 方法将数据中str转换int，float从而算法可以计算
# map方法，apply，transform

In [30]:
u = X['workclass'].unique()
u

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [33]:
np.argwhere(u == 'Local-gov')[0,0]

4

In [34]:
def convert(x):
    return np.argwhere(u == x)[0,0]
X['workclass'] = X['workclass'].map(convert)
X.head()

age  workclass  education_num      marital_status         occupation  \
0   39          0             13       Never-married       Adm-clerical   
1   50          1             13  Married-civ-spouse    Exec-managerial   
2   38          2              9            Divorced  Handlers-cleaners   
3   53          2              7  Married-civ-spouse  Handlers-cleaners   
4   28          2             13  Married-civ-spouse     Prof-specialty   

    relationship   race     sex  hours_per_week native_country  
0  Not-in-family  White    Male              40  United-States  
1        Husband  White    Male              13  United-States  
2  Not-in-family  White    Male              40  United-States  
3        Husband  Black    Male              40  United-States  
4           Wife  Black  Female              40           Cuba

In [36]:
cols = [ 'marital_status', 'occupation', 'relationship', 'race', 'sex','native_country']
for col in cols:
    u = X[col].unique()
    def convert(x):
        return np.argwhere(u == x)[0,0]
    X[col] = X[col].map(convert)
X.head()

age  workclass  education_num  marital_status  occupation  relationship  \
0   39          0             13               0           0             0   
1   50          1             13               1           1             1   
2   38          2              9               2           2             0   
3   53          2              7               1           2             1   
4   28          2             13               1           3             2   

   race  sex  hours_per_week  native_country  
0     0    0              40               0  
1     0    0              13               0  
2     0    0              40               0  
3     1    0              40               0  
4     1    1              40               1

In [43]:
knn = KNeighborsClassifier()
kFold = KFold(10)
knn = KNeighborsClassifier()
accuracy = 0
for train,test in kFold.split(X,y):
    knn.fit(X.loc[train],y[train])
    acc = knn.score(X.loc[test],y[test])
    accuracy += acc/10
print(accuracy)

0.7973345728987424


In [44]:
X.head()

age  workclass  education_num  marital_status  occupation  relationship  \
0   39          0             13               0           0             0   
1   50          1             13               1           1             1   
2   38          2              9               2           2             0   
3   53          2              7               1           2             1   
4   28          2             13               1           3             2   

   race  sex  hours_per_week  native_country  
0     0    0              40               0  
1     0    0              13               0  
2     0    0              40               0  
3     1    0              40               0  
4     1    1              40               1

In [45]:
y.unique()

array(['<=50K', '>50K'], dtype=object)

In [ ]:
# 从preprocessing 数据预处理中找一找有没有其他方法将str---------int,float类型
# 作业