In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix

data = np.genfromtxt("wine_data.csv", delimiter=",")
x_data = data[:,1:]
y_data = data[:,0]
print(x_data.shape)
print(y_data.shape)

(178, 13)
(178,)


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

mlp = MLPClassifier(hidden_layer_sizes=(100,50),max_iter=500)
mlp.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [ ]:
predictions = mlp.predict(x_test)
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        1.0       0.92      1.00      0.96        12
        2.0       1.00      0.91      0.95        22
        3.0       0.92      1.00      0.96        11

avg / total       0.96      0.96      0.96        45



In [ ]:
print(confusion_matrix(y_test,predictions))

[[12  0  0]
 [ 1 20  1]
 [ 0  0 11]]
