In [2]:
import numpy as np

from sklearn.linear_model import LinearRegression

import matplotlib.pyplot as plt
%matplotlib  inline

from sklearn import datasets

d:\python3.6.8\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
# 波士顿房价
boston = datasets.load_boston()

In [5]:
X = np.linspace(0,10,50).reshape(-1,1)
X

array([[ 0.        ],
       [ 0.20408163],
       [ 0.40816327],
       [ 0.6122449 ],
       [ 0.81632653],
       [ 1.02040816],
       [ 1.2244898 ],
       [ 1.42857143],
       [ 1.63265306],
       [ 1.83673469],
       [ 2.04081633],
       [ 2.24489796],
       [ 2.44897959],
       [ 2.65306122],
       [ 2.85714286],
       [ 3.06122449],
       [ 3.26530612],
       [ 3.46938776],
       [ 3.67346939],
       [ 3.87755102],
       [ 4.08163265],
       [ 4.28571429],
       [ 4.48979592],
       [ 4.69387755],
       [ 4.89795918],
       [ 5.10204082],
       [ 5.30612245],
       [ 5.51020408],
       [ 5.71428571],
       [ 5.91836735],
       [ 6.12244898],
       [ 6.32653061],
       [ 6.53061224],
       [ 6.73469388],
       [ 6.93877551],
       [ 7.14285714],
       [ 7.34693878],
       [ 7.55102041],
       [ 7.75510204],
       [ 7.95918367],
       [ 8.16326531],
       [ 8.36734694],
       [ 8.57142857],
       [ 8.7755102 ],
       [ 8.97959184],
       [ 9

In [6]:
y = np.random.randint(2,8,size = 1)*X
y

array([[ 0.        ],
       [ 1.2244898 ],
       [ 2.44897959],
       [ 3.67346939],
       [ 4.89795918],
       [ 6.12244898],
       [ 7.34693878],
       [ 8.57142857],
       [ 9.79591837],
       [11.02040816],
       [12.24489796],
       [13.46938776],
       [14.69387755],
       [15.91836735],
       [17.14285714],
       [18.36734694],
       [19.59183673],
       [20.81632653],
       [22.04081633],
       [23.26530612],
       [24.48979592],
       [25.71428571],
       [26.93877551],
       [28.16326531],
       [29.3877551 ],
       [30.6122449 ],
       [31.83673469],
       [33.06122449],
       [34.28571429],
       [35.51020408],
       [36.73469388],
       [37.95918367],
       [39.18367347],
       [40.40816327],
       [41.63265306],
       [42.85714286],
       [44.08163265],
       [45.30612245],
       [46.53061224],
       [47.75510204],
       [48.97959184],
       [50.20408163],
       [51.42857143],
       [52.65306122],
       [53.87755102],
       [55

In [8]:
y/X

d:\python3.6.8\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.]])

In [7]:
lr = LinearRegression()

lr.fit(X,y)
# coeficient 效率，斜率
# w ---->weight 权重，
lr.coef_

array([[6.]])

$$\hat{w} = (X^TX)^{-1}X^Ty$$

In [12]:
# 线性代数中的矩阵运算
np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

array([[6.]])

$$最小二乘法 H = \sum_{i = 0}^N(Xw - y)^2$$

$$2(Xw - y)X = 0$$

$$(Xw - y)XX^{-1} = 0X^{-1}$$

$$Xw - y = 0$$

$$Xw = y$$

$$X^TXw = X^Ty$$

$$(X^TX)^{-1}(X^TX)w = (X^TX)^{-1}X^Ty$$

$$Iw = (X^TX)^{-1}X^Ty$$

$$w = (X^TX)^{-1}X^Ty$$

In [19]:
X = boston['data']
y = boston['target']

In [20]:
X.shape

(506, 13)

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [23]:
X.shape

(506, 13)

In [22]:
lr = LinearRegression(fit_intercept=False)

lr.fit(X_train,y_train)
# 斜率个数：属性的个数决定
display(lr.coef_,lr.intercept_)

array([-0.1412295 ,  0.04181349, -0.01322025,  1.86963613, -4.15101845,
        6.06733637, -0.01337729, -1.09192302,  0.17925408, -0.00889826,
       -0.41013493,  0.01643046, -0.3599472 ])

0.0

In [26]:
# 算法预测的结果
lr.predict(X_test).round(2)[:25]

array([21.11, 17.72, 31.43,  2.33, 24.62, 19.41, 20.77,  8.16, 26.16,
       19.31, 20.68,  7.19, 43.46, 24.02, 21.2 , 17.67, 10.54, 14.64,
       27.81, 27.43, 22.87, 30.66, 19.62, 37.61, 30.9 ])

$$f(x) = w1*x1 + w2*x2 + …… + w13*x13$$

In [29]:
w = lr.coef_
w

array([-0.1412295 ,  0.04181349, -0.01322025,  1.86963613, -4.15101845,
        6.06733637, -0.01337729, -1.09192302,  0.17925408, -0.00889826,
       -0.41013493,  0.01643046, -0.3599472 ])

In [33]:
X_test.dot(w).round(2)[:25]

array([21.11, 17.72, 31.43,  2.33, 24.62, 19.41, 20.77,  8.16, 26.16,
       19.31, 20.68,  7.19, 43.46, 24.02, 21.2 , 17.67, 10.54, 14.64,
       27.81, 27.43, 22.87, 30.66, 19.62, 37.61, 30.9 ])

In [27]:
# '真实'的房价显示
y_test[:25]

array([16.4, 18.6, 41.3,  8.8, 22.8, 27.1, 18.7, 27.5, 22. , 14.1, 16.1,
        5. , 50. , 22.6, 13.8, 20.8, 12. , 12.8, 22.9, 26.5, 21.5, 29.9,
       18.3, 50. , 50. ])

In [34]:
lr = LinearRegression(fit_intercept=True)

lr.fit(X_train,y_train)

display(lr.coef_,lr.intercept_)

array([-1.41151959e-01,  4.11921987e-02, -1.40329665e-03,  1.62461478e+00,
       -1.74893870e+01,  3.95218799e+00, -4.11935673e-03, -1.60614632e+00,
        2.97047505e-01, -1.16287244e-02, -9.43595535e-01,  1.09847236e-02,
       -4.79093686e-01])

35.204261036207875

$$f(x) = w1*x1 + w2*x2 + …… + w13*x13 + b$$

In [35]:
lr.predict(X_test).round(2)[:15]

array([19.23, 16.17, 33.17,  3.79, 28.58, 19.67, 21.32, 13.91, 27.06,
       17.79, 18.98,  6.42, 43.27, 24.57, 20.47])

In [36]:
# 根据斜率和截距构造方程，进行求解的结果
(X_test.dot(lr.coef_) + lr.intercept_).round(2)[:15]

array([19.23, 16.17, 33.17,  3.79, 28.58, 19.67, 21.32, 13.91, 27.06,
       17.79, 18.98,  6.42, 43.27, 24.57, 20.47])